//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AplikacjeInternetoweEntities1 : DbContext
    {
        public AplikacjeInternetoweEntities1()
            : base("name=AplikacjeInternetoweEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DkPz> DkPz { get; set; }
        public virtual DbSet<DkPzPoz> DkPzPoz { get; set; }
        public virtual DbSet<DkSp> DkSp { get; set; }
        public virtual DbSet<DkSpPoz> DkSpPoz { get; set; }
        public virtual DbSet<DkWz> DkWz { get; set; }
        public virtual DbSet<DkWzPoz> DkWzPoz { get; set; }
        public virtual DbSet<DkZk> DkZk { get; set; }
        public virtual DbSet<DkZkPoz> DkZkPoz { get; set; }
        public virtual DbSet<Magazyny> Magazyny { get; set; }
        public virtual DbSet<MagazynyPoz> MagazynyPoz { get; set; }
        public virtual DbSet<Towary> Towary { get; set; }
        public virtual DbSet<Uzytkownicy> Uzytkownicy { get; set; }
        public virtual DbSet<ZMO> ZMO { get; set; }
        public virtual DbSet<ZMOPoz> ZMOPoz { get; set; }
        public virtual DbSet<ZMW> ZMW { get; set; }
        public virtual DbSet<ZMWPoz> ZMWPoz { get; set; }
    }
}
