//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DkWz
    {
        public long id { get; set; }
        public string kod { get; set; }
        public long idkh { get; set; }
        public Nullable<System.DateTime> data { get; set; }
    
        public virtual Uzytkownicy Uzytkownicy { get; set; }
    }
}
