//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DkWzPoz
    {
        public long id { get; set; }
        public long idDkWz { get; set; }
        public double ilosc { get; set; }
        public long idtw { get; set; }
        public long pozMag { get; set; }
    
        public virtual DkPz DkPz { get; set; }
        public virtual MagazynyPoz MagazynyPoz { get; set; }
        public virtual Towary Towary { get; set; }
    }
}
