//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MagazynyPoz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MagazynyPoz()
        {
            this.DkPzPoz = new HashSet<DkPzPoz>();
            this.DkWzPoz = new HashSet<DkWzPoz>();
        }
    
        public long id { get; set; }
        public long idtw { get; set; }
        public long idmg { get; set; }
        public double ilosc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DkPzPoz> DkPzPoz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DkWzPoz> DkWzPoz { get; set; }
        public virtual Magazyny Magazyny { get; set; }
        public virtual Towary Towary { get; set; }
    }
}
