//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZMOPoz
    {
        public long id { get; set; }
        public long idZMO { get; set; }
        public double netto { get; set; }
        public Nullable<double> podatek { get; set; }
        public Nullable<double> brutto { get; set; }
        public Nullable<double> ilosc { get; set; }
        public long idtw { get; set; }
    
        public virtual Towary Towary { get; set; }
        public virtual ZMO ZMO { get; set; }
    }
}
